---
# yamllint disable rule:line-length

# local-config: referenced, but not emitted by kustomize
apiVersion: v1
kind: ConfigMap
metadata:
  name: edpm-nodeset-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  root_password: cmVkaGF0Cg==
  preProvisioned: false
  baremetalSetTemplate:
    # osContainerImageUrl: taken_from_openstackversion registry-proxy.engineering.redhat.com/rh-osbs/rhoso18-edpm-hardened-uefi:18.0.0-17
    ctlplaneInterface: enp130s0f0
    cloudUserName: cloud-admin
    provisioningInterface: enp1s0
    bmhLabelSelector:
      app: openstack
    passwordSecret:
      name: baremetalset-password-secret
      namespace: openstack
  ssh_keys:
    # Authorized keys that will have access to the dataplane computes via SSH
    authorized: CHANGEME
    # The private key that will have access to the dataplane computes via SSH
    private: CHANGEME
    # The public key that will have access to the dataplane computes via SSH
    public: CHANGEME
  nodeset:
    ansible:
      ansibleUser: cloud-admin
      ansiblePort: 22
      ansibleVars:
        # CHANGEME -- see https://access.redhat.com/solutions/253273
        # edpm_bootstrap_command: |
        #       subscription-manager register --username <subscription_manager_username> \
        #         --password <subscription_manager_password>
        #       podman login -u <registry_username> -p <registry_password> registry.redhat.io
        timesync_ntp_servers:
          - hostname: clock.redhat.com
        # CPU pinning settings
        # edpm nfv ovs dpdk config
        # CHANGEME
        # yamllint disable-line rule:line-length
        edpm_kernel_args: "default_hugepagesz=1GB hugepagesz=1G hugepages=64 iommu=pt intel_iommu=on tsx=off isolcpus=2-19,22-39"
        edpm_tuned_max_power_cstate: c6
        edpm_network_config_nmstate: true
        edpm_network_config_hide_sensitive_logs: false
        edpm_tuned_profile: "cpu-partitioning-powersave"
        edpm_tuned_isolated_cores: "2-19,22-39"
        edpm_nova_libvirt_qemu_group: "hugetlbfs"
        edpm_ovs_dpdk_pmd_core_list: "2,3,22,23"
        edpm_ovs_dpdk_socket_memory: "4096"
        edpm_ovs_dpdk_memory_channels: "4"
        edpm_ovs_dpdk_vhost_postcopy_support: "true"
        edpm_ovn_bridge_mappings: ['dpdkmgmt:br-link0','dpdkdata0:br-dpdk0','dpdkdata1:br-dpdk1']
        # edpm nfv sriov config
        edpm_neutron_sriov_agent_SRIOV_NIC_physical_device_mappings: 'sriov1:enp6s0f2,sriov2:enp6s0f3,sriov-mlx-1:enp4s0f0np0,sriov-mlx-2:enp4s0f1np1'
        # edpm_network_config
        # These vars are edpm_network_config role vars
        edpm_network_config_os_net_config_mappings:
          # Need to provide nic mapping based on system uuid or system product name
          # here used systetm uuid
          compute-r730:
            dmiString: "system-product-name"
            id: "PowerEdge R730"
            nic1: "eno1"
            nic2: "eno2"
            nic3: "enp130s0f0"
            nic4: "enp130s0f1"
            nic5: "enp130s0f2"
            nic6: "enp130s0f3"
            nic7: "enp6s0f0"
            nic8: "enp6s0f1"
            nic9: "enp6s0f2"
            nic10: "enp6s0f3"
            nic11: "enp4s0f0np0"
            nic12: "enp4s0f1np1"
            nic13: "enp8s0f0np0"
            nic14: "enp8s0f1np1"
        edpm_network_config_template: |
          ---
          {% set mtu_list = [ctlplane_mtu] %}
          {% for network in nodeset_networks %}
          {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
          {%- endfor %}
          {% set min_viable_mtu = mtu_list | max %}
          network_config:
          - type: interface
            name: nic1
            use_dhcp: false
          - type: interface
            name: nic2
            use_dhcp: false
          - type: interface
            name: nic4
            use_dhcp: false
          - type: ovs_bridge
            name: {{ neutron_physical_bridge_name }}
            mtu: {{ min_viable_mtu }}
            use_dhcp: false
            dns_servers: {{ ctlplane_dns_nameservers }}
            domain: {{ dns_search_domains }}
            addresses:
            - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
            routes: {{ ctlplane_host_routes }}
            members:
            - type: interface
              name: nic3
              mtu: {{ min_viable_mtu }}
              # force the MAC address of the bridge to this interface
              primary: true
          {% for network in nodeset_networks if network not in ['external', 'tenant'] %}
            - type: vlan
              mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
              vlan_id: {{ lookup('vars', networks_lower[network] ~ '_vlan_id') }}
              addresses:
                - ip_netmask: {{ lookup('vars', networks_lower[network] ~ '_ip') }}/{{ lookup('vars', networks_lower[network] ~ '_cidr') }}
              routes: {{ lookup('vars', networks_lower[network] ~ '_host_routes') }}
          {% endfor %}
          - type: ovs_user_bridge
            name: br-link0
            use_dhcp: false
            ovs_extra: "set port br-link0 tag={{ lookup('vars', networks_lower['tenant'] ~ '_vlan_id') }}"
            addresses:
              - ip_netmask: {{ lookup('vars', networks_lower['tenant'] ~ '_ip') }}/{{ lookup('vars', networks_lower['tenant'] ~ '_cidr') }}
            mtu: {{ lookup('vars', networks_lower['tenant'] ~ '_mtu') }}
            rx_queue: 1
            members:
            - type: ovs_dpdk_bond
              name: dpdkbond0
              mtu: 9000
              rx_queue: 1
              ovs_extra: "set port dpdkbond0 bond_mode=balance-slb"
              members:
              - type: ovs_dpdk_port
                name: dpdk0
                members:
                - type: interface
                  name: nic7
              - type: ovs_dpdk_port
                name: dpdk1
                members:
                - type: interface
                  name: nic8
          - type: ovs_user_bridge
            name: br-dpdk0
            use_dhcp: false
            mtu: 9000
            rx_queue: 1
            members:
            - type: ovs_dpdk_port
              name: dpdk2
              members:
              - type: interface
                name: nic5
          - type: ovs_user_bridge
            name: br-dpdk1
            use_dhcp: false
            mtu: 9000
            rx_queue: 1
            members:
            - type: ovs_dpdk_port
              name: dpdk3
              members:
              - type: interface
                name: nic6
          - type: sriov_pf
            name: nic9
            numvfs: 5
            mtu: 9000
            use_dhcp: false
            promisc: true
          - type: sriov_pf
            name: nic10
            numvfs: 5
            mtu: 9000
            use_dhcp: false
            promisc: true
          - type: sriov_pf
            name: nic11
            numvfs: 5
            mtu: 9000
            use_dhcp: false
            promisc: true
          - type: sriov_pf
            name: nic12
            numvfs: 5
            mtu: 9000
            use_dhcp: false
            promisc: true
          - type: interface
            name: nic13
            use_dhcp: false
          - type: interface
            name: nic14
            use_dhcp: false

        # These vars are for the network config templates themselves and are
        # considered EDPM network defaults.
        neutron_physical_bridge_name: br-ex
        neutron_public_interface_name: nic1
        # edpm_nodes_validation
        edpm_nodes_validation_validate_controllers_icmp: false
        edpm_neutron_ovn_agent_image: registry-proxy.engineering.redhat.com/rh-osbs/rhoso18-openstack-neutron-ovn-agent:18.0_20240510.1
        edpm_nodes_validation_validate_gateway_icmp: false
        dns_search_domains: []
        gather_facts: false
        enable_debug: false
        # edpm firewall, change the allowed CIDR if needed
        edpm_sshd_configure_firewall: true
        edpm_sshd_allowed_ranges:
          - 192.168.122.0/24
        # SELinux module
        edpm_selinux_mode: enforcing
        edpm_bootstrap_command: |-
          # root CA
          cd /etc/pki/ca-trust/source/anchors/
          curl -LOk https://certs.corp.redhat.com/RH-IT-Root-CA.crt
          curl -LOk https://certs.corp.redhat.com/certs/2022-IT-Root-CA.pem
          update-ca-trust

          # install rhos-release repos
          dnf --nogpgcheck --repofrompath=rhos-release,http://download.devel.redhat.com/rcm-guest/puddles/OpenStack/rhos-release/ --repo=rhos-release install -y rhos-release
          rhos-release ceph-7.0-rhel-9 -r 9.4

          # Issue #2 - edpm_bootstrap fails if we don't update 'container-selinux'
          dnf update -y

          rpm -ivh --nosignature http://download.devel.redhat.com/rcm-guest/puddles/OpenStack/rhos-release/rhos-release-latest.noarch.rpm
          rhos-release ceph-7.0-rhel-9 -r 9.4
          curl -o /etc/yum.repos.d/delorean.repo https://osp-trunk.hosted.upshift.rdu2.redhat.com/rhel9-osp18/current-podified/delorean.repo
          echo "[osptrunk-candidate-deps]" >> "/etc/yum.repos.d/osptrunk-candidate-deps.repo"
          echo "name=osptrunk-candidate-deps" >> "/etc/yum.repos.d/osptrunk-candidate-deps.repo"
          echo "baseurl=http://download.eng.bos.redhat.com/brewroot/repos/rhos-18.0-rhel-9-trunk-candidate/latest/x86_64/" >> "/etc/yum.repos.d/osptrunk-candidate-deps.repo"
          echo "gpgcheck=0" >> /etc/yum.repos.d/osptrunk-candidate-deps.repo
          echo "enabled=1" >> /etc/yum.repos.d/osptrunk-candidate-deps.repo
          echo "priority=1" >> /etc/yum.repos.d/osptrunk-candidate-deps.repo
        edpm_ceph_hci_pre_enabled_services:
          - ceph_mon
          - ceph_mgr
          - ceph_osd
          - ceph_rgw
          - ceph_nfs
          - ceph_rgw_frontend
          - ceph_nfs_frontend
        storage_mtu: 9000
        storage_mgmt_mtu: 9000
        storage_mgmt_vlan_id: 145
        storage_mgmt_cidr: "24"
        storage_mgmt_host_routes: []
    networks:
      - defaultRoute: true
        name: ctlplane
        subnetName: subnet1
      - name: internalapi
        subnetName: subnet1
      - name: storage
        subnetName: subnet1
      - name: tenant
        subnetName: subnet1
    nodes:
      edpm-compute-0:
        ansible:
          ansibleHost: 192.168.122.100
        hostName: edpm-compute-0
        networks:
          - defaultRoute: true
            fixedIP: 192.168.122.100
            name: ctlplane
            subnetName: subnet1
          - name: internalapi
            subnetName: subnet1
          - name: storage
            subnetName: subnet1
          - name: storagemgmt
            subnetName: subnet1
          - name: tenant
            subnetName: subnet1
    services:
      - bootstrap
      - download-cache
      - reboot-os
      - configure-ovs-dpdk
      - configure-network
      - validate-network
      - install-os
      - ceph-hci-pre
      - configure-os
      - ssh-known-hosts
      - run-os
      - install-certs
      - ovn
      - neutron-ovn-igmp
      - neutron-metadata
      - neutron-sriov
      - libvirt
      - nova-custom-ovsdpdksriov
      - telemetry
  nova:
    compute:
      conf: |
        [DEFAULT]
        reserved_host_memory_mb = 4096
        [compute]
        cpu_shared_set = 0,1,20,21
        cpu_dedicated_set = 4-19,24-39
        [neutron]
        physnets = dpdkdata1
        [neutron_physnet_dpdkdata1]
        numa_nodes = 1
    migration:
      ssh_keys:
        private: CHANGEME
        public: CHANGEME
    pci:
      # yamllint disable-line rule:line-length
      conf: |
        [pci]
        device_spec = {"address": "0000:06:00.2", "physical_network":"sriov1", "trusted":"true"}
        device_spec = {"address": "0000:06:00.3", "physical_network":"sriov2", "trusted":"true"}
        device_spec = {"address": "0000:04:00.0", "physical_network":"sriov-mlx-1", "trusted":"true"}
        device_spec = {"address": "0000:04:00.1", "physical_network":"sriov-mlx-2", "trusted":"true"}
  neutron:
    igmp:
      conf: |
        [ovs]
        igmp_snooping_enable = False
