# local-config: referenced, but not emitted by kustomize
#
# CHANGEME:
#
# - Change network_vlan_ranges based on EDPM OvS DPDK SRIOV environment.
# - change numa_nodes in the neutron and neutron_tunnel section
# based on DPDK NIC's and NUMA alignment in the OvS DPDK & SRIOV compute node.
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  preserveJobs: false
  neutron:
    customServiceConfig: |
      [DEFAULT]
      global_physnet_mtu = 9000
      [ml2]
      mechanism_drivers = ovn,sriovnicswitch
      path_mtu = 0
      [ovn]
      vhost_sock_dir = /var/lib/vhost_sockets
      enable_distributed_floating_ip=False
      [ml2_type_vlan]
      network_vlan_ranges = access:428:428,dpdkmgmt:145:149,dpdkdata0:145:149,dpdkdata1:145:149,sriov1:145:149,sriov2:145:149,sriov-mlx-1:145:149,sriov-mlx-2:145:149
      [ovs]
      igmp_snooping_enable = True
      [oslo_policy]
      policy_file=/etc/neutron/policy.d/policy.yaml
  ovn:
    ovnController:
      nicMappings:
        access: enp7s0
        dpdkmgmt: ospbr
        dpdkdata0: ospbr
        dpdkdata1: ospbr
  glance:
    customServiceConfig: |
      [DEFAULT]
      enabled_backends = default_backend:swift
      [glance_store]
      default_backend = default_backend
      [default_backend]
      swift_store_create_container_on_put = True
      swift_store_auth_version = 3
      swift_store_auth_address = {{ .KeystoneInternalURL }}
      swift_store_endpoint_type = internalURL
      swift_store_user = service:glance
      swift_store_key = {{ .ServicePassword }}
    default:
      replicas: 1
  swift:
    enabled: true
  telemetry:
    enabled: true
    template:
      ceilometer:
        enabled: true
  nova:
    schedulerServiceTemplate:
      customServiceConfig: |
        [filter_scheduler]
        enabled_filters = AvailabilityZoneFilter,ComputeFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,PciPassthroughFilter,NUMATopologyFilter,AggregateInstanceExtraSpecsFilter
  extraMounts:
    - extraVol:
        - propagation:
            - NeutronAPI
          extraVolType: Policy
          volumes:
            - name: neutron-policy
              configMap:
                name: neutron-policy
          mounts:
            - name: neutron-policy
              mountPath: /etc/neutron/policy.d
              readOnly: true
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: dpdkdata0
  name: dpdkdata0
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "dpdkdata0",
      "type": "bridge",
      "bridge": "ospbr",
      "ipam": {}
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: dpdkdata1
  name: dpdkdata1
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "dpdkdata1",
      "type": "bridge",
      "bridge": "ospbr",
      "ipam": {}
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: dpdkmgmt
  name: dpdkmgmt
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "dpdkmgmt",
      "type": "bridge",
      "bridge": "ospbr",
      "ipam": {}
    }
