---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane-pre-ceph
  # - https://github.com/openstack-k8s-operators/architecture/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane-pre-ceph?ref=main
  ## It's possible to replace ../../../../../dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane-pre-ceph with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - nncp/values.yaml
  - service-values.yaml
